version: 2

sources:
  - name: raw
    database: "{{ target.database }}"
    schema: RAW
    tables:
      - name: crm_opportunities
      - name: subscriptions
      - name: invoices
      - name: payments

